### ISSUE TITLE
Services can't access Smart Key

### ISSUE THREAD

**Issue by mustafahanyitworx** [ahmadabousetta/Egypt-tax-invoice-api#3]
Thanks for your effort, I'm facing an issue when try to execute signer as windows service, the windows service can't access the smart key, we got slot not found

**Comment by ahmadabousetta** [comment]
Hi. You're welcome. 
Please do the following:
1. Confirm the signer is working well when called normally, not as a service.
2. Clarify the steps you follow to create the service.
3. Copy the exact fault message.

Thanks

**Comment by mustafahanyitworx** [comment]
It's working normally, I got No slot found when I execute it from the Task Schedule.

**Comment by ahmadabousetta** [comment]
Copy the exact fault message please

**Comment by ahmadabousetta** [comment]
@mustafahanyitworx please read carefully the remarks in the file SubmitInvoices.bat and follow the same concept in the scheduler.
https://github.com/ahmadabousetta/Egypt-tax-invoice-api/blob/main/c%23_signer/SubmitInvoices.bat
